import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "../components/general/Navbar";
import { AuthProvider } from "@/components/general/AuthProvider";
import { Poppins } from 'next/font/google';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], // Or specific weights you need
  subsets: ['latin'], // Or other subsets as needed
  variable: '--font-poppins', // Optional, for CSS variables
  display: 'swap', // Optional, for better performance
});

export const metadata: Metadata = {
  title: "NextJs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en" className={poppins.variable}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased
          max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 style-poppins`}
        >
          <Navbar />
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
